name: web3dart_multicall
description: A starting point for Dart libraries or applications.
version: 1.0.3

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  web3dart:
    git:
      url: git@github.com:BitizenWallet/web3dart.git
      ref: master

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
